name = "LittleGibbs"
uuid = "a851fd22-abba-402a-8658-27d0862bc5ee"
authors = ["Philipp Gabler <phipsgabler@users.noreply.github.com>"]
version = "0.1.0"

[deps]
AbstractMCMC = "80f14c24-f653-4e6a-9b94-39d6b0f70001"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[extras]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"

[targets]
test = ["Distributions"]
